spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.163.164:3306/sell?useSSL=false&characterEncoding=utf-8&useUnicode=true
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
server:
  context-path: /sell